name: resume
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  universal_platform: ^1.0.0
  get_it: ^7.2.0
  dio: ^4.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  another_flushbar: ^1.10.29
  pretty_dio_logger: ^1.1.1
  font_awesome_flutter: ^9.0.0
  flutter_linkify: ^6.0.0
  expansion_tile_card: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  google_fonts:
  lottie:
  url_launcher:
  shared_preferences:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:   
    - assets/images/pic.jpeg
    - assets/images/
    - assets/anim/scanning.json

  

  